### ISSUE TITLE
30cc5285d6bc297b9ca633042957def0 exec failed: Cannot retrieve credentials in unknown state

### ISSUE THREAD

**Issue by 0penSourcerer** [sfx101/deck#108] opened 2022-10-12 15:51 UTC
Platform: macOS Monterey 12.6 (21G115)
Hardware: MacBook Air (M1, 2020)

I am unable to actually launch the Deck application. The Terminal output shows that Multipass has installed correctly, and it also shows that the following error is preventing a proper launch:

"30cc5285d6bc297b9ca633042957def0                                                
exec failed: Cannot retrieve credentials in unknown state"

I am unsure of how to fix this error and am unable to use Deck.

**Comment by nabad600** [comment] 2022-10-12 16:11
Hi @0penSourcerer, 
Thanks for using DECK. Please verify the multipass install in your system. Run the below-mentioned command
`multipass --version` 
can you share the output 
If already installed please uninstall, run the below command to uninstall the same
` sudo sh "/Library/Application Support/com.canonical.multipass/uninstall.sh" `
Then download the DECK package with the below link
``
https://github.com/deck-app/stable-releases/releases/download/v4.2.0/DECK-4.2.0-mac-arm64.dmg
``
and install it. I hope this will resolve the issue.
we'd be happy to help.

**Comment by 0penSourcerer** [comment] 2022-10-12 16:43
multipass --version output:

"multipass   1.8.1+mac
multipassd  1.8.1+mac

#########################################################################################
Multipass 1.10.1 bug fix release
Fix regression in `multipass exec` command

Go here for more information: https://github.com/canonical/multipass/releases/tag/v1.10.1
#########################################################################################"

I also ran the multipass uninstaller and re-installed Deck using the above URL to no avail. I'm still having the exact same error.

**Comment by nabad600** [comment] 2022-10-12 18:23
Hi @0penSourcerer,
Thanks for your reply, Please uninstall multipass, and DECK run the below command to uninstall the same
` sudo sh "/Library/Application Support/com.canonical.multipass/uninstall.sh" `

After that Install the new version multipass below command to install the same
` curl https://raw.githubusercontent.com/nabad600/multipass-script/master/install.sh | sh `

after that install DECK
we'd be happy to help.

**Comment by 0penSourcerer** [comment] 2022-10-12 20:28
After following the instructions provided above, my multipass --version output is:

"multipass   1.10.1+mac
multipassd  1.10.1+mac"

When I launch Deck and hit Install, I'm still getting the same error:

"30cc5285d6bc297b9ca633042957def0
exec failed: Cannot retrieve credentials in unknown state"

**Comment by nabad600** [comment] 2022-10-13 05:45
Hi @0penSourcerer,
It seems SSH is blocked in some way. Please check below link for your reference 
[Issues caused by MacOS update](https://multipass.run/docs/troubleshoot-networking#heading--issues-caused-by-macos-update)
https://github.com/canonical/multipass/issues/539

**Comment by 0penSourcerer** [comment] 2022-10-13 19:57
I looked at both of the links above. I don't have a firewall or VPN on while I'm trying to launch Deck and I still get the same error. I'm not sure what to do. I've never been able to get Deck to launch even one time.

**Comment by 0penSourcerer** [comment] 2022-10-13 20:40
multipass version output:

"multipass   1.10.1+mac
multipassd  1.10.1+mac"

multipass list output:

"Name                    State             IPv4             Image
deck-app                Unknown           --               Ubuntu 22.04 LTS"

multipass exec deck-app -- cat/etc/auto.projects output:

"exec failed: Cannot retrieve credentials in unknown state"

**Comment by nabad600** [comment] 2022-10-14 07:19
Hi @0penSourcerer ,

Please can you run the terminal and share the output?
1. `multipass find`
2. `multipass networks`
3. `multipass launch`

**Note:- Please check the firewall off in your system.**

![image](https://user-images.githubusercontent.com/67466982/195785988-18975267-c73c-4682-8a92-53d3494706b8.png)

**Comment by 0penSourcerer** [comment] 2022-10-14 19:18
multipass find output:

"Image                       Aliases           Version          Description
18.04                       bionic            20221010         Ubuntu 18.04 LTS
20.04                       focal             20221010         Ubuntu 20.04 LTS
22.04                       jammy,lts         20221014         Ubuntu 22.04 LTS
anbox-cloud-appliance                         latest           Anbox Cloud Appliance
charm-dev                                     latest           A development and testing environment for charmers
docker                                        latest           A Docker environment with Portainer and related tools
jellyfin                                      latest           Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media.
minikube                                      latest           minikube is local Kubernetes"

multipass networks output:

"Name     Type         Description
bridge0  bridge       Network bridge with en1, en2
en0      wifi         Wi-Fi
en1      thunderbolt  Thunderbolt 1
en2      thunderbolt  Thunderbolt 2
en3      ethernet     Ethernet Adapter (en3)
en4      ethernet     Ethernet Adapter (en4)"

multipass launch output:

"Launched: sociable-paddlefish"

**Comment by nabad600** [comment] 2023-03-06 15:33
Hi @0penSourcerer,
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.

**Closed** 2023-03-07 12:29 UTC
