### ISSUE TITLE
Open in secure browser (SSL) will not work

### ISSUE THREAD

**Issue by CamKem** [sfx101/deck#111] opened 2022-11-06 04:28 UTC
When building a project, using laravel, mysql or any of the available project and then trying to launch the project using the "Open in secure browser" link will always result in an error.

I have tried it using Safari, Chrome, Firefox & Brave browsers and the same results with all of them, so I know its not browser specific.

There might be some configuration with my system or other dev environment that is clashing, I am using MacOS Monterey if it helps.

I don't know if this is the appropriate place for this support request, however this is the only forum that has been set up for the app that I could find. I suggest starting up a Slack community if that is possible, so that we can better communicate for support issues.

**Comment by CamKem** [comment] 2022-11-06 04:30
![Image of the error](https://user-images.githubusercontent.com/112100521/200154249-a311701c-b911-4ccd-8252-7e59b1d53461.jpeg)

**Comment by Subhajit9836** [comment] 2022-11-06 04:52
Hi @CamKem

First of all, let me assure you that you are in the right place. We regularly monitor each and every comment we get in this forum. We'll try to recreate the issue you are facing on your side and get back to you as soon as possible.

Thanks for reaching out to git support team.

**Comment by Subhajit9836** [comment] 2022-11-06 07:41
Hello again

I see that you are using a dash "-" in the domain name. Did you try without the dash?

Previously, our users found issues with a dash in the domain name. Please try without that if you haven't already. If you still face the same problem, please send a reply here and we'll try to troubleshoot the issue.

Thanks

**Comment by CamKem** [comment] 2022-11-06 09:36
Hello, yes I tried using projects both with and without "-", and using straight numerals or straight letters too but with no success. Thanks in advance for the support.

**Comment by CamKem** [comment] 2022-11-06 09:37
> Hello again
> 
> I see that you are using a dash "-" in the domain name. Did you try without the dash?
> 
> Previously, our users found issues with a dash in the domain name. Please try without that if you haven't already. If you still face the same problem, please send a reply here and we'll try to troubleshoot the issue.
> 
> Thanks

Hello, yes I tried using projects both with and without "-", and using straight numerals or straight letters too but with no success. Thanks in advance for the support.

**Comment by nabad600** [comment] 2022-11-08 01:53
Greetings, @CamKem
Your comment is greatly appreciated. Could you please let me know any application is using the 80/443 ports?
or check open your terminal and type the command "sudo lsof -PiTCP -sTCP:LISTEN" and check 80/443. If use anther application, then please close the application
Please check how many "DECK" application open in your system
![image](https://user-images.githubusercontent.com/67466982/200192104-5b9feda0-5bc6-403e-a96b-f52113b46562.png)

We hope the problem is fixed.
![image](https://user-images.githubusercontent.com/67466982/200192206-edc76985-fa40-408a-a57a-22127df227c1.png)
![image](https://user-images.githubusercontent.com/67466982/200192636-f8f085de-1671-4545-b366-3c3140c01caa.png)

**Comment by CamKem** [comment] 2022-11-09 04:24
Hello, 

Thanks for your help.

Unfortunately the problem is persisting, I am not very familiar with terminal com
![20221109 030420 1](https://user-images.githubusercontent.com/112100521/200738109-7b30d707-6a31-4d9c-8c9c-f8d28b12786c.jpeg)

mands, so I put the details in your wanted and took a screenshot.

Can you please look at them and let me know if you see anything that could be causing the issue?

Thanks in advance.

![20221109 030623 1](https://user-images.githubusercontent.com/112100521/200738207-3a9f24d3-abe2-4119-ac5d-6d112a337ee1.jpeg)
![20221109 030420 1](https://user-images.githubusercontent.com/112100521/200738192-e5f87930-ae75-4572-aded-9d64331223aa.jpeg)
![20221109 030440 1](https://user-images.githubusercontent.com/112100521/200738198-2836eb08-8e1e-4fc4-bb58-a50eb6a32a8b.jpeg)

**Comment by nabad600** [comment] 2022-11-09 16:47
Hello, @CamKem
Thank you for sharing your snapshot. We noticed that your system is using HTTP on port 80. Do you use XAMPP or WAMP?
![image](https://user-images.githubusercontent.com/67466982/200887360-8e284842-1211-4831-bd9b-b1d7c74149f3.png)

Under DECK application "Settings", is it possible to share "Docker engine"?

**Comment by CamKem** [comment] 2022-11-10 21:42
Should I be using the remote engine or docker desktop option?

Currently Docker option in settings is unticked.
@nabad600

**Comment by CamKem** [comment] 2022-11-11 10:23
Also to answer the question I dont use XAMPP or WAMP for web servers.
I was just using deck, and hoping that it could be used in place of web server software.

Otherwise, I mainly use laravel so I can always use the built in web server.

**Comment by nabad600** [comment] 2022-11-11 12:35
Hello, @CamKem
I appreciate you sharing this knowledge.
If you're using a built-in web server, like IIS, and it's using port 80 or 443, please disable it or use different port other than 80/443, since DECK requires the mentioned ports.

**Comment by nabad600** [comment] 2022-12-01 02:29
Hi @CamKem 
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.

**Closed** 2022-12-05 03:45 UTC
